#ifndef QMLAPPLICATION_GLOBAL_H
#define QMLAPPLICATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QMLAPPLICATION_LIBRARY)
#  define QMLAPPLICATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QMLAPPLICATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QMLAPPLICATION_GLOBAL_H
